# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitTestExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 5.6.0'
  # Pods for UnitTestExample

  target 'UnitTestExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitTestExampleUITests' do
    # Pods for testing
  end

end
